insert into "COMPANY" ("ID", "NAME") values(10001, 'Intel')
insert into "COMPANY" ("ID", "NAME") values(10002, 'AMD')
insert into "COMPANY" ("ID", "NAME") values(10003, 'Microsoft')
insert into "COMPANY" ("ID", "NAME") values(10004, 'Google')
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2001, 'Brian', 'Krzanich', 10001)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2002, 'Lisa T.', 'Su', 10002)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2003, 'Mark', 'Papermaster', 10002)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2004, 'Bill', 'Gates', 10003)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2005, 'Nathan', 'Myhrvold', 10003)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2006, 'John W.', 'Thompson', 10003)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2007, 'Edward', 'Snowden', null)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2008, 'Julian', 'Assange', null)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2009, 'Larry', 'Page', 10004)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2010, 'Sergey', 'Brin', 10004)
insert into "ORDERING" ("ID", "ORDERNUMBER") values(5001, 1)
insert into "ORDERING" ("ID", "ORDERNUMBER") values(5002, 2)
insert into "ORDERING" ("ID", "ORDERNUMBER") values(5003, 3)
insert into "ORDERING" ("ID", "ORDERNUMBER") values(5004, 4)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6001, 'Gartenhandschuhe', 5001)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6002, 'Gartenschlauch', 5001)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6003, 'Rasenmäher', 5002)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6004, 'Rosenschere', 5002)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6005, 'Gieskanne', 5003)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6006, 'Gartenhandschuhe', 5003)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6007, 'Heckenschere', 5004)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6008, 'Wasserpumpe', 5004)
insert into "MODULE" ("ID", "TITLE") values(8001, 'Ägypten und der alte Orient')
insert into "MODULE" ("ID", "TITLE") values(8002, 'Ägyptologie')
insert into "MODULE" ("ID", "TITLE") values(8003, 'Altorientalistik')
insert into "MODULE" ("ID", "TITLE") values(8004, 'Amerikanistik ')
insert into "MODULE" ("ID", "TITLE") values(8005, 'Anglistik')
insert into "MODULE" ("ID", "TITLE") values(8006, 'Arabistik')
insert into "STUDENT" ("ID", "FIRSTNAME", "LASTNAME") values (9001, 'Bruno', 'Mars')
insert into "STUDENT" ("ID", "FIRSTNAME", "LASTNAME") values (9002, 'Herbi', 'Hancock')
insert into "STUDENT" ("ID", "FIRSTNAME", "LASTNAME") values (9003, 'Steve', 'Wonder')
insert into "STUDENT" ("ID", "FIRSTNAME", "LASTNAME") values (9004, 'Paul', 'McCartney')
insert into "STUDENT" ("ID", "FIRSTNAME", "LASTNAME") values (9005, 'Roger', 'Hodgson')
insert into "STUDENT" ("ID", "FIRSTNAME", "LASTNAME") values (9006, 'Neil', 'Rogers')
insert into "STUDENT_MODULE" ("M_ID", "S_ID") values (8001, 9001)
insert into "STUDENT_MODULE" ("M_ID", "S_ID") values (8002, 9002)
insert into "STUDENT_MODULE" ("M_ID", "S_ID") values (8002, 9003)
insert into "STUDENT_MODULE" ("M_ID", "S_ID") values (8003, 9003)
insert into "STUDENT_MODULE" ("M_ID", "S_ID") values (8004, 9004)

